# SPDX-License-Identifier: Unlicense
#
# Generates a CTest include file from the test binary's own registry
# (`--list-tests`). Runs as the yapb_testhost POST_BUILD step, so adding a
# scenario never requires touching CMake: drop the .cpp, rebuild, ctest sees it.
#
# Required -D args:
#   TEST_EXECUTABLE  path to the test host binary
#   TEST_OUTPUT      file to (re)generate (a CTest TEST_INCLUDE_FILES entry)
#   TEST_GAMEDIR     staging root that holds cstrike/dlls/...
#   TEST_WINDOWS     ON/OFF (selects the per-test home env var)

if(NOT DEFINED TEST_EXECUTABLE OR NOT DEFINED TEST_OUTPUT OR NOT DEFINED TEST_GAMEDIR)
    message(FATAL_ERROR "DiscoverTests.cmake: TEST_EXECUTABLE, TEST_OUTPUT and TEST_GAMEDIR are required")
endif()

if(TEST_WINDOWS)
    set(_home "USERPROFILE")
else()
    set(_home "HOME")
endif()
set(_env "YB_SINGLE_THREADED=1;${_home}=${TEST_GAMEDIR}/home")

file(WRITE "${TEST_OUTPUT}" "# generated by DiscoverTests.cmake; do not edit\n")

execute_process(
    COMMAND "${TEST_EXECUTABLE}" --list-tests
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _listed
    ERROR_QUIET
)

if(NOT _result EQUAL 0)
    message(WARNING "DiscoverTests.cmake: '${TEST_EXECUTABLE} --list-tests' failed (${_result})")
    return()
endif()

string(REPLACE "\r\n" "\n" _listed "${_listed}")
string(REPLACE "\n" ";" _names "${_listed}")

foreach(_name IN LISTS _names)
    string(STRIP "${_name}" _name)

    if(_name STREQUAL "")
        continue()
    endif()

    # non-default gamedir staging is a bracket tag on the case name
    set(_workdir "${TEST_GAMEDIR}")

    if(_name MATCHES "\\[regame\\]")
        set(_workdir "${TEST_GAMEDIR}-regame")
    elseif(_name MATCHES "\\[modern\\]")
        set(_workdir "${TEST_GAMEDIR}-modern")
    endif()

    string(TOLOWER "${_name}" _lower)
    string(REGEX REPLACE "[^a-z0-9]+" "_" _id "${_lower}")
    string(REGEX REPLACE "^_+" "" _id "${_id}")
    string(REGEX REPLACE "_+$" "" _id "${_id}")

    # ctest include files use the positional add_test form (not NAME/COMMAND)
    file(APPEND "${TEST_OUTPUT}"
        "add_test(yapb_${_id} \"${TEST_EXECUTABLE}\" \"--filter=${_name}\")\n"
        "set_tests_properties(yapb_${_id} PROPERTIES TIMEOUT 300 WORKING_DIRECTORY \"${_workdir}\" ENVIRONMENT \"${_env}\")\n"
    )
endforeach()
