language: cpp
dist: bionic

compiler:
  - clang

addons:
  apt:
    packages:
      - libc6-dev-i386
      - linux-libc-dev
      - gcc-multilib
      - g++-multilib
os:
  - linux
  - osx
  
before_script:
  - sed -i.bak "s/unspecified_hash/$(git rev-parse HEAD 2>/dev/null)/g;s/unspecified_author/$(git log --pretty="%ae" -1 2>/dev/null)/g;s/0000/$(git rev-list HEAD --count 2>/dev/null)/g" include/resource.h && rm include/resource.h.bak

script:
  - cd project && CC=clang && make all

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
  -   curl -F "key=$CI_KEY" -F "mode=build" -F "type=release" -F "lib=@./release/yapb.so" https://yapb.ru/agent/ci.php
  -   curl -F "key=$CI_KEY" -F "mode=build" -F "type=debug" -F "lib=@./debug/yapb.so" https://yapb.ru/agent/ci.php
  - fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
  -   curl -F "key=$CI_KEY" -F "mode=build" -F "type=release" -F "lib=@./release/yapb.dylib" https://yapb.ru/agent/ci.php
  -   curl -F "key=$CI_KEY" -F "mode=build" -F "type=debug" -F "lib=@./debug/yapb.dylib" https://yapb.ru/agent/ci.php
  - fi
