//
// YaPB, started from PODBot by Count Floyd
// Maintained by YaPB Team <yapb@jeefo.net>
//
// SPDX-License-Identifier: Unlicense
//

#pragma once

// client flags
namespace bot {

enum class ClientFlags : int32_t {
  Used = ystl::bit (0),
  Alive = ystl::bit (1),
  Admin = ystl::bit (2),
  Icon = ystl::bit (3),
  Bot = ystl::bit (4)
};
YSTL_ENABLE_ENUM_FLAGS (ClientFlags);

// icon show flags
enum class ClientIcon : int32_t {
  Visible = ystl::bit (1)
};
YSTL_ENABLE_ENUM_FLAGS (ClientIcon);

// icon struct for radio/chat
struct RadioChatIcon {
  ClientIcon flags {}; // flag holding chatter icons
  float timestamp {}; // timers for chatter icons
};

// array of clients struct
struct Client {
  edict_t *ent {}; // pointer to actual edict
  ystl::Vector origin {}; // position in the world
  Team team { Team::Spectator }; // bot team
  Team team2 { Team::Spectator }; // real bot team in free for all mode (csdm)
  ClientFlags flags {}; // client flags
  MenuId MenuId {}; // identifier to opened menu
  RadioChat radio {}; // radio orders
  ystl::FixedArray<RadioChatIcon, kGameMaxPlayers> icon {}; // radiochat icon wearing
  ClientNoise noise {}; // noise generated by client

public:
  bool IsSameTeam (Team ct) const {
    return team == ct;
  }

  bool IsEnemyTeam (Team ct) const {
    return team != ct;
  }

  bool IsTeammate (Team ct, edict_t *self) const {
    return IsUsedAndAlive () && IsSameTeam (ct) && ent != self;
  }

  bool IsInRadius (const ystl::Vector &pos, float radius_sq) const {
    return origin.distance_sq (pos) < radius_sq;
  }

  bool IsOutsideRadius (const ystl::Vector &pos, float radius_sq) const {
    return origin.distance_sq (pos) > radius_sq;
  }

  bool IsUsed () const {
    return ent != nullptr && has_flag (flags, ClientFlags::Used);
  }

  bool IsBot () const {
    return IsUsed () && has_flag (flags, ClientFlags::Bot);
  }

  bool IsHuman () const {
    return IsUsed () && !has_flag (flags, ClientFlags::Bot);
  }

  bool IsUsedAndAlive () const {
    return IsUsed () && has_flag (flags, ClientFlags::Alive);
  }

  bool IsUsedAndNot (edict_t *self) const {
    return IsUsed () && ent != self;
  }

  bool IsUsedAnd (edict_t *self) const {
    return IsUsed () && ent == self;
  }

  bool IsTeammate2 (Team ct, edict_t *self) const {
    return IsUsed () && team2 == ct && ent != self;
  }
};

// cliens access manager
class ClientManager : public ystl::Singleton<ClientManager> {
private:
  ystl::SmallArray<Client, kGameMaxPlayers + 1> clients_ {};

public:
  explicit ClientManager () {
    clients_.resize (kGameMaxPlayers + 1);
  }
  ~ClientManager () = default;

public:
  // update stats on clients
  void Update ();

public:
  // indexed access (non-const)
  Client &operator[] (const int32_t index) {
    return clients_[index];
  }

  // indexed access (const)
  const Client &operator[] (const int32_t index) const {
    return clients_[index];
  }

  // payer edict access (non-const)
  Client &operator[] (edict_t *ent);

  // payer edict  access (const)
  const Client &operator[] (edict_t *ent) const;

public:
  Client *begin () {
    return clients_.begin ();
  }

  const Client *begin () const {
    return clients_.begin ();
  }

  Client *end () {
    return clients_.end ();
  }

  const Client *end () const {
    return clients_.end ();
  }
};

// expose globals
YSTL_EXPOSE_GLOBAL_SINGLETON (ClientManager, clients);

} // namespace bot
