#!/usr/bin/env python3
#
# YaPB, started from PODBot by Count Floyd
# Maintained by YaPB Team <yapb@jeefo.net>
#
# SPDX-License-Identifier: Unlicense
#
# Generates the amx mod x include (yapb.inc).
# Natives come from ext/amxx/yapb_amxx.cpp (each carries a doc block plus a
# "// @native <pawn prototype>;" line), enums are read straight from the
# bot headers so the two never drift. Run manually before committing.
#
#   python3 tools/gen_amxx_inc.py           # regenerate
#   python3 tools/gen_amxx_inc.py --check    # fail if out of date
#

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'ext', 'amxx', 'yapb_amxx.cpp')
OUTPUT = os.path.join(ROOT, 'cfg', 'addons', 'amxmodx', 'scripting', 'include', 'yapb.inc')

HEADER = '''//
// YaPB, started from PODBot by Count Floyd
// Maintained by YaPB Team <yapb@jeefo.net>
//
// SPDX-License-Identifier: Unlicense
//
// Generated by tools/gen_amxx_inc.py from ext/amxx/yapb_amxx.cpp and the bot
// headers. Do not edit.
//

#if defined _yapb_included
  #endinput
#endif

#define _yapb_included

#include <cstrike>

#pragma reqlib yapb
#if !defined AMXMODX_NOAUTOLOAD
  #pragma loadlib yapb
#endif

#define INVALID_NODE_INDEX -1
#define INVALID_ENTITY_INDEX 0
'''

NATIVE_RE = re.compile(r'^\s*//\s*@native\s+(.+?)\s*$')
ARRAY_RE = re.compile(r'\{\s*"(yb_\w+)"')

# pawn enum name -> (header, c++ enum name, names to skip)
ENUM_SOURCES = (
    ('NodeFlag', 'inc/graph.h', 'NodeFlag', ('Invalid',)),
    ('NodeType', 'inc/graph.h', 'PointType', ('Count',)),
    ('Difficulty', 'inc/constant.h', 'Difficulty', ('Invalid',)),
    ('Personality', 'inc/constant.h', 'Personality', ('Invalid',)),
    ('Task', 'inc/tasks.h', 'TaskId', ('Num',)),
)


def read(path):
    with open(os.path.join(ROOT, path), 'r', encoding='utf-8') as handle:
        return handle.read()


def parse_cpp_enum(text, name):
    match = re.search(r'enum\s+class\s+' + re.escape(name) + r'\s*(?::[^{]*)?\{(.*?)\}', text, re.S)
    if not match:
        raise SystemExit('enum %s not found' % name)

    entries = []
    values = {}
    nextval = 0

    body = re.sub(r'//[^\n]*', '', match.group(1))

    for chunk in body.split(','):
        line = chunk.strip()
        if not line:
            continue

        if '=' in line:
            ident, expr = (part.strip() for part in line.split('=', 1))
        else:
            ident, expr = line, None

        if not re.match(r'^\w+$', ident):
            continue

        if expr is None:
            value, printable = nextval, str(nextval)
        else:
            bit = re.match(r'ystl::bit\s*\(\s*(\d+)\s*\)', expr)
            if bit:
                value, printable = 1 << int(bit.group(1)), '(1 << %s)' % bit.group(1)
            elif re.match(r'^-?\d+$', expr):
                value, printable = int(expr), expr
            elif expr in values:
                value, printable = values[expr], str(values[expr])
            else:
                value, printable = nextval, str(nextval)

        values[ident] = value
        nextval = value + 1
        entries.append((ident, printable))

    return entries


def render_enum(pawn_name, header, cpp_name, skip):
    entries = [e for e in parse_cpp_enum(read(header), cpp_name) if e[0] not in skip]
    lines = ['enum %s {' % pawn_name]

    for i, (ident, printable) in enumerate(entries):
        comma = ',' if i + 1 < len(entries) else ''
        lines.append('  %s = %s%s' % (ident, printable, comma))

    lines.append('}')
    return '\n'.join(lines)


def preceding_doc(lines, i):
    # collect a /** ... */ block sitting directly above line i
    end = i - 1
    if end < 0 or not lines[end].strip().endswith('*/'):
        return ''
    start = end
    while start >= 0 and not lines[start].strip().startswith('/**'):
        start -= 1
    if start < 0:
        return ''
    return '\n'.join(lines[start:end + 1])


# pawn has no namespaces: strip c++ qualifications (ystl::, bot::, ...) from doc prose
DOC_NS_RE = re.compile(r'\b[A-Za-z_]\w*::')

def pawn_doc(doc):
    # strip c++ qualifications, then dedent to column 0 (docs inherit the c++ namespace indent)
    lines = DOC_NS_RE.sub('', doc).split('\n')
    indents = [len(line) - len(line.lstrip()) for line in lines if line.strip()]

    if indents:
        cut = min(indents)
        lines = [line[cut:] if line.strip() else line for line in lines]
    return '\n'.join(lines)


def parse_natives(lines):
    natives = []
    for i, line in enumerate(lines):
        match = NATIVE_RE.match(line)
        if not match:
            continue

        proto = match.group(1).rstrip(';').strip()
        name = re.match(r'(?:\w+\s*:\s*)?(\w+)\s*\(', proto)
        natives.append((name.group(1) if name else proto, proto, preceding_doc(lines, i)))
    return natives


def collect_table_names(text):
    names = set()
    started = False
    for line in text.splitlines():
        if 'bot_natives[]' in line:
            started = True
        if started:
            for match in ARRAY_RE.finditer(line):
                names.add(match.group(1))
    return names


def generate():
    text = read('ext/amxx/yapb_amxx.cpp')
    lines = text.splitlines()

    natives = parse_natives(lines)
    table = collect_table_names(text)
    declared = set(name for name, _, _ in natives)

    if table != declared:
        missing = table - declared
        extra = declared - table
        raise SystemExit('native/table mismatch: missing docs=%s, missing table=%s'
                         % (sorted(missing), sorted(extra)))

    out = [HEADER]
    out.append('\n\n'.join(render_enum(*spec) for spec in ENUM_SOURCES))
    out.append('')

    for _, proto, doc in natives:
        if doc:
            out.append(pawn_doc(doc))
        out.append('native %s;' % proto)
        out.append('')

    return '\n'.join(out).rstrip('\n') + '\n'


def main():
    content = generate()

    if '--check' in sys.argv:
        current = ''
        if os.path.exists(OUTPUT):
            with open(OUTPUT, 'r', encoding='utf-8') as handle:
                current = handle.read()
        if current != content:
            print('%s is out of date, run: python3 tools/gen_amxx_inc.py' % OUTPUT)
            return 1
        print('%s is up to date' % OUTPUT)
        return 0

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(content)
    print('generated %s' % OUTPUT)
    return 0


if __name__ == '__main__':
    sys.exit(main())
